# Generated by Django 3.2.5 on 2023-11-09 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='building_name',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
