# Generated by Django 3.2.5 on 2023-11-09 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_location_building_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='building_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
