# Generated by Django 3.2.5 on 2023-11-09 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_location_building_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='building_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
